---
services:
  cache:
    container_name: cache
    hostname: cache
    image: redis:latest
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./gateway/redis/data:/data
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
    # driver_opts:
    #   com.docker.network.driver.mtu: 1450
  backend:
    internal: true

