version: "3.7"

services:
  gateway:
    image: registry.hbp.link/hip/gateway:latest
    environment:
      - REMOTE_APP_API=${REMOTE_APP_API}
      - REMOTE_APP_BASIC_AUTH=${REMOTE_APP_BASIC_AUTH}
      - PRIVATE_WEBDAV_URL=${PRIVATE_WEBDAV_URL}
      - COLLAB_WEBDAV_URL=${COLLAB_WEBDAV_URL}
      - COLLAB_WEBDAV_USERNAME=${COLLAB_WEBDAV_USERNAME}
      - COLLAB_WEBDAV_PASSWORD=${COLLAB_WEBDAV_PASSWORD}
      - HOSTNAME=${NEXTCLOUD_VIRTUAL_HOST}
    expose:
      - 4000
    networks:
      - nextcloud-docker_frontend
      - nextcloud-docker_backend
    command: npm run start

  cache:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./gateway/redis/data:/data
    expose: 
     - 6379
    networks:
      - nextcloud-docker_frontend

networks:
  nextcloud-docker_backend:
    external: true
  nextcloud-docker_frontend:
    external: true


