version: "3.7"

services:
  hip:
    build: 
      context: ./hip 
      target: base
    working_dir: /base
    restart: always
    volumes:
      - ./hip:/base
      - /base/node_modules
    environment:
      - NODE_ENV=development
      - HOSTNAME=${HOSTNAME}
      - GATEWAY_API=${GATEWAY_API}
      - MATOMO_URL_BASE=${MATOMO_URL_BASE}
      - MATOMO_SITE_ID=${MATOMO_SITE_ID}
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - frontend

  
