version: "3.2"

services:
  cache:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./gateway/redis/data:/data
    expose: 
     - 6379
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - nextcloud-docker_frontend

networks:
  nextcloud-docker_backend:
    external: true
  nextcloud-docker_frontend:
    external: true


