version: "3.7"

services:
  hip:
    build: 
      context: ./hip 
      target: base
    working_dir: /base
    restart: always
    volumes:
      - ./hip:/base
      - /base/node_modules
    environment:
      - NODE_ENV=development
      - HOSTNAME=${HOSTNAME}
      - GATEWAY_API=${GATEWAY_API}
      - MATOMO_URL_BASE=${MATOMO_URL_BASE}
      - MATOMO_SITE_ID=${MATOMO_SITE_ID}
    expose:
      - 3000
    command: npm run start
    networks:
      - nextcloud-docker_frontend

  cache:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./gateway/redis/data:/data
    expose: 
      - 6379
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - nextcloud-docker_frontend

networks:
  nextcloud-docker_frontend:
    external: true
